import { Geist, Jua } from "next/font/google";
import "./globals.css";

const jua = Jua({ 
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full ${jua.className} antialiased`}

    >
      <body className="min-h-full flex flex-col" style={{
        backgroundColor: "#e7d4b1",
        backgroundImage: `url("/bg-01.webp")`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        fontFamily: 'jua'
      }}>{children}</body>
    </html>
  );
}
